// Confirm Payment
export const CONFIRM_PAYMENT_REQUEST = 'sys.CONFIRM_PAYMENT_REQUEST';
export const CONFIRM_PAYMENT_SUCCESS = 'sys.CONFIRM_PAYMENT_SUCCESS';
export const CONFIRM_PAYMENT_FAILURE = 'sys.CONFIRM_PAYMENT_FAILURE';
export const RESET_CONFIRM_PAYMENT = 'sys.RESET_CONFIRM_PAYMENT';

// Initiate STK Push
export const INITIATE_STK_PUSH_REQUEST = 'sys.INITIATE_STK_PUSH_REQUEST';
export const INITIATE_STK_PUSH_SUCCESS = 'sys.INITIATE_STK_PUSH_SUCCESS';
export const INITIATE_STK_PUSH_FAILURE = 'sys.INITIATE_STK_PUSH_FAILURE';
export const RESET_INITIATE_STK_PUSH = 'sys.RESET_INITIATE_STK_PUSH';
