// Get all my TRANSACTIONS
export const GET_ALL_TRANSACTIONS_REQUEST = 'transactions.GET_ALL_TRANSACTIONS_REQUEST';
export const GET_ALL_TRANSACTIONS_SUCCESS = 'transactions.GET_ALL_TRANSACTIONS_SUCCESS';
export const GET_ALL_TRANSACTIONS_FAILURE = 'transactions.GET_ALL_TRANSACTIONS_FAILURE';
export const RESET_GET_ALL_TRANSACTIONS = 'transactions.RESET_GET_ALL_TRANSACTIONS';

// Get all my TRANSACTIONS
export const GET_ALL_MY_TRANSACTIONS_REQUEST = 'transactions.GET_ALL_MY_TRANSACTIONS_REQUEST';
export const GET_ALL_MY_TRANSACTIONS_SUCCESS = 'transactions.GET_ALL_MY_TRANSACTIONS_SUCCESS';
export const GET_ALL_MY_TRANSACTIONS_FAILURE = 'transactions.GET_ALL_MY_TRANSACTIONS_FAILURE';
export const RESET_GET_ALL_MY_TRANSACTIONS = 'transactions.RESET_GET_ALL_MY_TRANSACTIONS';

// Get my TRANSACTION by TRANSACTION id
export const GET_MY_TRANSACTION_REQUEST = 'transactions.GET_MY_TRANSACTION_REQUEST';
export const GET_MY_TRANSACTION_SUCCESS = 'transactions.GET_MY_TRANSACTION_SUCCESS';
export const GET_MY_TRANSACTION_FAILURE = 'transactions.GET_MY_TRANSACTION_FAILURE';
export const RESET_GET_MY_TRANSACTION = 'transactions.RESET_GET_MY_TRANSACTION';
