// Log In
export const LOGIN_REQUEST = 'auth.LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth.LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth.LOGIN_FAILURE';
export const RESET_LOGIN = 'auth.RESET_LOGIN';

// Authenticate User
export const AUTHENTICATE_USER_REQUEST = 'auth.AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'auth.AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'auth.AUTHENTICATE_USER_FAILURE';
export const RESET_AUTHENTICATE_USER = 'auth.RESET_AUTHENTICATE_USER';


// Reset Password
export const RESET_PWD_REQUEST = 'auth.RESET_PWD_REQUEST';
export const RESET_PWD_SUCCESS = 'auth.RESET_PWD_SUCCESS';
export const RESET_PWD_FAILURE = 'auth.RESET_PWD_FAILURE';
export const RESET_RESET_PWD = 'auth.RESET_RESET_PWD';


///

// NEW ACTION TYPES


export const SET_USER = 'SET_USER';
export const SET_AUTHENTICATION_STATUS = 'SET_AUTHENTICATION_STATUS';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const LOGOUT_USER = 'LOGOUT_USER';

		/* Revoke access token */
export const REVOKE_TOKEN_REQUESTING = 'REVOKE_TOKEN_REQUESTING';
export const REVOKE_TOKEN_REQUEST_SUCCESS = 'REVOKE_TOKEN_REQUEST_SUCCESS';
export const REVOKE_TOKEN_REQUEST_ERROR = 'REVOKE_TOKEN_REQUEST_ERROR';
export const RESET_REVOKE_TOKEN_REQUEST = 'RESET_REVOKE_TOKEN_REQUEST';
