// Log In
export const LOGIN_REQUEST = 'auth.LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'auth.LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth.LOGIN_FAILURE';
export const RESET_LOGIN = 'auth.RESET_LOGIN';

// Authenticate User
export const AUTHENTICATE_USER_REQUEST = 'auth.AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'auth.AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILURE = 'auth.AUTHENTICATE_USER_FAILURE';
export const RESET_AUTHENTICATE_USER = 'auth.RESET_AUTHENTICATE_USER';


// Reset Password
export const RESET_PWD_REQUEST = 'auth.RESET_PWD_REQUEST';
export const RESET_PWD_SUCCESS = 'auth.RESET_PWD_SUCCESS';
export const RESET_PWD_FAILURE = 'auth.RESET_PWD_FAILURE';
export const RESET_RESET_PWD = 'auth.RESET_RESET_PWD';


