// Get all documents records
export const GET_ALL_MY_DOCUMENTS_REQUEST = 'documents.GET_ALL_MY_DOCUMENTS_REQUEST';
export const GET_ALL_MY_DOCUMENTS_SUCCESS = 'documents.GET_ALL_MY_DOCUMENTS_SUCCESS';
export const GET_ALL_MY_DOCUMENTS_FAILURE = 'documents.GET_ALL_MY_DOCUMENTS_FAILURE';
export const RESET_GET_ALL_MY_DOCUMENTS = 'documents.RESET_GET_ALL_MY_DOCUMENTS';

// Get a document's record
export const GET_MY_DOCUMENT_REQUEST = 'documents.GET_MY_DOCUMENT_REQUEST';
export const GET_MY_DOCUMENT_SUCCESS = 'documents.GET_MY_DOCUMENT_SUCCESS';
export const GET_MY_DOCUMENT_FAILURE = 'documents.GET_MY_DOCUMENT_FAILURE';
export const RESET_GET_MY_DOCUMENT = 'documents.RESET_GET_MY_DOCUMENT';

// Create document
export const CREATE_MY_DOCUMENT_REQUEST = 'documents.CREATE_MY_DOCUMENT_REQUEST';
export const CREATE_MY_DOCUMENT_SUCCESS = 'documents.CREATE_MY_DOCUMENT_SUCCESS';
export const CREATE_MY_DOCUMENT_FAILURE = 'documents.CREATE_MY_DOCUMENT_FAILURE';
export const RESET_CREATE_MY_DOCUMENT = 'documents.RESET_CREATE_MY_DOCUMENT';

// Update document
export const UPDATE_MY_DOCUMENT_REQUEST = 'documents.UPDATE_MY_DOCUMENT_REQUEST';
export const UPDATE_MY_DOCUMENT_SUCCESS = 'documents.UPDATE_MY_DOCUMENT_SUCCESS';
export const UPDATE_MY_DOCUMENT_FAILURE = 'documents.UPDATE_MY_DOCUMENT_FAILURE';
export const RESET_UPDATE_MY_DOCUMENT = 'documents.RESET_UPDATE_MY_DOCUMENT';

// Delete document
export const DELETE_MY_DOCUMENT_REQUEST = 'documents.DELETE_MY_DOCUMENT_REQUEST';
export const DELETE_MY_DOCUMENT_SUCCESS = 'documents.DELETE_MY_DOCUMENT_SUCCESS';
export const DELETE_MY_DOCUMENT_FAILURE = 'documents.DELETE_MY_DOCUMENT_FAILURE';
export const RESET_DELETE_MY_DOCUMENT = 'documents.RESET_DELETE_MY_DOCUMENT';
