// Get all my LOANS
export const GET_ALL_MY_LOANS_REQUEST = 'loans.GET_ALL_MY_LOANS_REQUEST';
export const GET_ALL_MY_LOANS_SUCCESS = 'loans.GET_ALL_MY_LOANS_SUCCESS';
export const GET_ALL_MY_LOANS_FAILURE = 'loans.GET_ALL_MY_LOANS_FAILURE';
export const RESET_GET_ALL_MY_LOANS = 'loans.RESET_GET_ALL_MY_LOANS';

// Get my LOAN by LOAN id
export const GET_MY_LOAN_REQUEST = 'loans.GET_MY_LOAN_REQUEST';
export const GET_MY_LOAN_SUCCESS = 'loans.GET_MY_LOAN_SUCCESS';
export const GET_MY_LOAN_FAILURE = 'loans.GET_MY_LOAN_FAILURE';
export const RESET_GET_MY_LOAN = 'loans.RESET_GET_MY_LOAN';

// Get all loan types
export const GET_LOAN_TYPES_REQUEST = 'loans.GET_LOAN_TYPES_REQUEST';
export const GET_LOAN_TYPES_SUCCESS = 'loans.GET_LOAN_TYPES_SUCCESS';
export const GET_LOAN_TYPES_FAILURE = 'loans.GET_LOAN_TYPES_FAILURE';
export const RESET_GET_LOAN_TYPES = 'loans.RESET_GET_LOAN_TYPES';

// Get all loan stati
export const GET_LOAN_STATI_REQUEST = 'loans.GET_LOAN_STATI_REQUEST';
export const GET_LOAN_STATI_SUCCESS = 'loans.GET_LOAN_STATI_SUCCESS';
export const GET_LOAN_STATI_FAILURE = 'loans.GET_LOAN_STATI_FAILURE';
export const RESET_GET_LOAN_STATI = 'loans.RESET_GET_LOAN_STATI';

// Apply Loan
export const APPLY_LOAN_REQUEST = 'loans.APPLY_LOAN_REQUEST';
export const APPLY_LOAN_SUCCESS = 'loans.APPLY_LOAN_SUCCESS';
export const APPLY_LOAN_FAILURE = 'loans.APPLY_LOAN_FAILURE';
export const RESET_APPLY_LOAN = 'loans.RESET_APPLY_LOAN';

// Get all my Guarantors
export const GET_ALL_MY_GUARANTORS_REQUEST = 'loans.GET_ALL_MY_GUARANTORS_REQUEST';
export const GET_ALL_MY_GUARANTORS_SUCCESS = 'loans.GET_ALL_MY_GUARANTORS_SUCCESS';
export const GET_ALL_MY_GUARANTORS_FAILURE = 'loans.GET_ALL_MY_GUARANTORS_FAILURE';
export const RESET_GET_ALL_MY_GUARANTORS = 'loans.RESET_GET_ALL_MY_GUARANTORS';

// View Guarantorship Request
export const GUARANTORSHIP_REQUEST_REQUEST = 'loans.GUARANTORSHIP_REQUEST_REQUEST';
export const GUARANTORSHIP_REQUEST_SUCCESS = 'loans.GUARANTORSHIP_REQUEST_SUCCESS';
export const GUARANTORSHIP_REQUEST_FAILURE = 'loans.GUARANTORSHIP_REQUEST_FAILURE';
export const RESET_GUARANTORSHIP_REQUEST = 'loans.RESET_GUARANTORSHIP_REQUEST';

// Update Guarantorship Request
export const UPDATE_GUARANTORSHIP_REQUEST_REQUEST = 'loans.UPDATE_GUARANTORSHIP_REQUEST_REQUEST';
export const UPDATE_GUARANTORSHIP_REQUEST_SUCCESS = 'loans.UPDATE_GUARANTORSHIP_REQUEST_SUCCESS';
export const UPDATE_GUARANTORSHIP_REQUEST_FAILURE = 'loans.UPDATE_GUARANTORSHIP_REQUEST_FAILURE';
export const RESET_UPDATE_GUARANTORSHIP_REQUEST = 'loans.RESET_UPDATE_GUARANTORSHIP_REQUEST';
